Fixed issue #33. Added Code of Conduct and spaces.
tessel/gps-a2235h pull request #36
Opened 2017-07-03 09:45 UTC by mittalshravika

2017-07-03 15:04 UTC, HipsterBrown approved these changes

2017-07-03 22:19 UTC, Frijol requested changes

2017-07-03 22:19 UTC, Frijol commented on README.md
> +*  &#x20;<a href="#api-gps-setCoordinateFormat-options-callback-Sets-coordinate-output-notation" name="api-gps-setCoordinateFormat-options-callback-Sets-coordinate-output-notation"> </a> gps<b>.setCo
Please leave `#` formatting! See note in RFID repo

2017-07-04 18:17 UTC, Frijol approved these changes

2017-07-04 18:18 UTC, merged